sudo: required

notifications:
  email: false

language: rust

before_install:
  - git clone https://github.com/stpettersens/netsh.git
  - cd netsh
  - cargo build --release
  - sudo cp target/release/netsh /usr/bin/_netsh
  - cd ..
  - sudo apt-get install -y rubygems
  - sudo gem install os
  - ruby --version
  - rake --version

script:
  - rake
  - rake data
  - rake test
