sudo: required

notifications:
  email: false

language: rust

before_install:
  - git clone https://github.com/bmc/daemonize.git
  - git clone https://github.com/stpettersens/netsh.git
  - git clone https://github.com/stpettersens/full-monkey.git
  - cd netsh
  - cargo build --release
  - sudo cp target/release/netsh /usr/bin/_netsh
  - cd ..
  - cd daemonize
  - sh configure
  - make
  - sudo make install
  - cd ..
  - cd full-monkey
  - sudo apt-get install -y rubygems
  - sudo gem install os
  - rake
  - sudo cp fm /usr/bin
  - cd ..
  - sudo apt-get install -y php5-cgi
  - sudo curl -s https://getcaddy.com | bash
  - php-cgi --version
  - caddy -version
  - ruby --version
  - rake --version

script:
  - rake configure
  - rake
  - rake -f ci_rakefile.rb data
  - rake server
  - rake test
